language: python

python:
  - "3.6"

services:
  - postgresql
  
before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver

env:
  - DJANGO_SETTINGS_MODULE="OpenFoodFacts_project.settings"

install:
  - 'pip install pipenv'
  - 'pipenv install'

before_script:
  - psql "CREATE USER rayane;"
  - psql -c "CREATE DATABASE projet_huit;" -U rayane

script:
  - ./manage.py test